// nic_pwa_svelte/src/components/Irrigation.svelte
<script>
    import { machineStatus } from '../store';
</script>

<h1>Smart Irrigation</h1>

{#if $machineStatus}
<h2>Mode: {$machineStatus.mode}</h2>
<h3>Active Cycle: {$machineStatus.activeCycle}</h3>
<ul>
    {#each $machineStatus.sectors as sector}
    <li>Sector {sector.id} - {sector.progress}% Watered</li>
    {/each}
</ul>
{:else}
<p>Loading...</p>
{/if}

// nic_pwa_preact/src/components/Irrigation.jsx
import { h } from 'preact';

const Irrigation = ({ machineStatus }) => {
  const { mode, activeCycle, sectors } = machineStatus;

  return (
    <div>
      <h1>Smart Irrigation</h1>
      <h2>Mode: {mode}</h2>
      <h3>Active Cycle: {activeCycle}</h3>
      <ul>
        {sectors.map((sector) => (
          <li key={sector.id}>
            Sector {sector.id} - {sector.progress}% Watered
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Irrigation;
