// nic_pwa_vue/src/components/Irrigation.vue
<template>
    <div>
      <h1>Machine Status</h1>
      <p>Mode: {{ machineStatus.mode }}</p>
      <p>Active Cycle: {{ machineStatus.activeCycle }}</p>
  
      <h2>Sector Progress</h2>
      <div v-for="sector in machineStatus.sectors" :key="sector.id">
        <p>Sector {{ sector.id }}: {{ sector.progress }}%</p>
        <progress :value="sector.progress" max="100"></progress>
      </div>
    </div>
  </template>
  
  <script>
  import { mapGetters, mapActions } from 'vuex';
  
  export default {
    computed: {
      ...mapGetters(['getMachineStatus']),
      machineStatus() {
        return this.getMachineStatus;
      },
    },
    created() {
      this.fetchMachineStatus();
    },
    methods: {
      ...mapActions(['fetchMachineStatus']),
    },
  };
  </script>

// nic_pwa_preact/src/components/Irrigation.jsx
import { h } from 'preact';

const Irrigation = ({ machineStatus }) => {
  const { mode, activeCycle, sectors } = machineStatus;

  return (
    <div>
      <h1>Smart Irrigation</h1>
      <h2>Mode: {mode}</h2>
      <h3>Active Cycle: {activeCycle}</h3>
      <ul>
        {sectors.map((sector) => (
          <li key={sector.id}>
            Sector {sector.id} - {sector.progress}% Watered
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Irrigation;
